WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
FPS = 60

SPAWN_START_X = WINDOW_WIDTH

OBSTACLE_SPAWN_MIN_GAP = 450
OBSTACLE_SPAWN_MAX_GAP = 750
COIN_SPAWN_MIN_GAP = 250
COIN_SPAWN_MAX_GAP = 500

STATE_MENU = 'menu'
STATE_PLAYING = 'playing'
STATE_PAUSE = 'pause'
STATE_GAME_OVER = 'game_over'

PLAYER_SCALE = 2
PLAYER_SPEED = 4
PLAYER_MOVE_LIMIT = 100

ANIMATION_SPEED = 0.15
ANIMATION_FRAMES_COUNT = 4

BACKGROUND_SPEED = 2

GROUND_Y = 500
JUMP_SPEED = -16
GRAVITY = 1

OBSTACLE_SIZE = (70, 70)
OBSTACLE_SPEED = 5
OBSTACLE_MIN_DISTANCE = 100
OBSTACLE_MAX_DISTANCE = 700

COIN_SIZE = (40, 40)
COIN_SPEED = 5
COIN_MIN_DISTANCE = 300
COIN_MAX_DISTANCE = 700
COIN_MIN_HEIGHT = 260
COIN_MAX_HEIGHT = 450

PLAYER_HITBOX_INFLATE = (-40, -30)
OBSTACLE_HITBOX_INFLATE = (-30, -40)
COIN_HITBOX_INFLATE = (-15, -15)
